apiVersion: v1
kind: Pod
metadata:
  name: cert-test
spec:
  containers:
  - name: test
    image: ${VERIFY_IMG}
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: certs
      mountPath: /var/run/certs
  volumes:
  - name: certs
    projected:
      sources:
      - podCertificate:
          signerName: "example.com/pod-signer"
          keyType: ECDSAP384
          credentialBundlePath: pod.pem
      - clusterTrustBundle:
          name: "example.com:pod-signer:ca"
          path: ca.crt
